# Generated by Django 5.2.4 on 2025-07-06 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Travel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_country", models.CharField(max_length=50)),
                ("origin_city", models.CharField(max_length=50)),
                ("destination_country", models.CharField(max_length=50)),
                ("destination_city", models.CharField(max_length=50)),
                ("departure_date", models.DateField()),
                (
                    "transport_type",
                    models.CharField(
                        choices=[("car", "Car"), ("bus", "Bus"), ("van", "Van")],
                        max_length=10,
                    ),
                ),
                ("available_seats", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
