# Generated by Django 5.2.4 on 2025-07-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="country",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="verification_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
